import type { Metadata } from "next";
import Link from "next/link";

import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXTAUTH_URL ?? "http://localhost:3000"),
  title: {
    default: "Voice of Finance - Insights from the world's finance interviews",
    template: "%s | Voice of Finance",
  },
  description:
    "AI-powered financial news: we turn finance interviews on YouTube into fact-checked summaries, deep dives and market analysis.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-full flex-col">
        <Providers>
          <Navbar />
          <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8">{children}</main>
          <footer className="border-t border-slate-200 bg-white py-6 text-center text-xs text-slate-500">
            <p>
              Voice of Finance articles are generated by AI from public interviews and linked to their sources. They
              are not investment advice.
            </p>
            <p className="mt-1">
              <Link href="/pricing" className="hover:underline">
                Pricing
              </Link>{" "}
              ·{" "}
              <Link href="/community" className="hover:underline">
                Community
              </Link>
            </p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
